---
name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed for progressive mode to work
      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@v6

  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - geerlingguy/docker-debian11-ansible # bullseye (stable)
          - geerlingguy/docker-debian10-ansible # buster (oldstable)
          - geerlingguy/docker-debian9-ansible # stretch LTS (oldoldstable)
          - geerlingguy/docker-debian8-ansible # jessie LTS (archived)
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed for progressive mode to work
      - name: Run molecule
        uses: gofrolist/molecule-action@v2
        env:
          IMAGE: ${{ matrix.image }}
